### ISSUE TITLE
Local Dapr secrets file not found after 1.0.1-rc.0.6

### ISSUE THREAD

**Issue by Deltids** [man-group/dapr-sidekick-dotnet#38]
## Expected Behavior

Local dapr secrets file is found and loaded

## Actual Behavior

Local dapr secrets file is not found

## Steps to Reproduce the Problem

- Navigate to all -> samples -> AspNetCore -> ConsulSample -> ConsolSample.Sender
- Create ./dapr/components/localSecretStore.yaml

``````
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: dapr.secrets.local
  - name: nestedSeparator
    value: ":"
``````
- Create ./dapr.secrets.local
``````
{
}
``````
Run application and check the logs
![image](https://user-images.githubusercontent.com/20363682/149902054-f3bbfbeb-5d0d-4200-840f-c04a6039beee.png)

- Open ConsulSample.Sender.csproj
- Change version
``````
  <ItemGroup>
<!--    <ProjectReference Include="..\..\..\..\src\Man.Dapr.Sidekick.AspNetCore\Man.Dapr.Sidekick.AspNetCore.csproj" />-->
    <PackageReference Include="Man.Dapr.Sidekick.AspNetCore" Version="1.0.1-rc.0.6" />
  </ItemGroup>
``````

Start application and see that there are no errors in the debug logs.
